from enum import IntEnum, auto, unique

@unique
class MapSetupAssetId(IntEnum):

    @classmethod
    def name_for_value(cls, value):
        if value in cls._value2member_map_:
            return cls(value).name
        return None

    MAP_SETUP_09F6_CUTSCENE_TWO_YEARS_HAVE_PASSED = 0x9F6
    MAP_SETUP_09F7_CUTSCENE_DRILL_STARTS = 0x9F7
    MAP_SETUP_09F8_CUTSCENE_DRILL_GOES_THROUGH_BOULDERS = 0x9F8
    MAP_SETUP_09F9_CUTSCENE_MAGIC_TO_LIFT_BOULDER = 0x9F9
    MAP_SETUP_09FA_CUTSCENE_REVENGE_IS_MINE = 0x9FA
    MAP_SETUP_09FB_CUTSCENE_WITCHES_LEAVE_SPIRAL_MOUNTAIN = 0x9FB
    MAP_SETUP_09FC_CUTSCENE_HOUSE_DESTROYED = 0x9FC
    MAP_SETUP_09FD_CUTSCENE_PLAYING_POKER = 0x9FD
    MAP_SETUP_09FE_CUTSCENE_EARTHQUAKE = 0x9FE
    MAP_SETUP_09FF_CUTSCENE_IT_STOPPED = 0x9FF
    MAP_SETUP_0A00_CUTSCENE_GET_OUT_OF_THE_HOUSE = 0xA00
    MAP_SETUP_0A01_CUTSCENE_COME_ON = 0xA01
    MAP_SETUP_0A02_GRUNTILDAS_LAIR_ENTRANCE = 0xA02
    MAP_SETUP_0A03_SPIRAL_MOUNTAIN_BEHIND_WATERFALL = 0xA03
    MAP_SETUP_0A04_SPIRAL_MOUNTAIN_MAIN = 0xA04
    #
    MAP_SETUP_0A0B_MAYAHEM_TEMPLE_WUMBAS_WIGWAM = 0xA0B
    MAP_SETUP_0A0C_MAYAHEM_TEMPLE_MUMBOS_SKULL = 0xA0C
    MAP_SETUP_0A0D_MAYAHEM_TEMPLE_MAIN = 0xA0D
    MAP_SETUP_0A0E_MAYAHEM_TEMPLE_PRISON_COMPOUND = 0xA0E
    MAP_SETUP_0A0F_MAYAHEM_TEMPLE_COLUMNS_VAULT = 0xA0F
    MAP_SETUP_0A10_MAYAHEM_TEMPLE_MAYAN_KICKBALL_STADIUM = 0xA10
    MAP_SETUP_0A11_MAYAHEM_TEMPLE_CODE_CHAMBER = 0xA11
    #
    MAP_SETUP_0A19_MAYAHEM_TEMPLE_JADE_SNAKE_GROVE = 0xA19
    MAP_SETUP_0A1A_MAYAHEM_TEMPLE_TREASURE_CHAMBER = 0xA1A
    MAP_SETUP_0A1B_MAYAHEM_TEMPLE_KICKBALL_ARENA_1 = 0xA1B
    MAP_SETUP_0A1C_GLITTER_GULCH_MINE_MAIN = 0xA1C
    MAP_SETUP_0A1D_MAYAHEM_TEMPLE_KICKBALL_ARENA_2 = 0xA1D
    MAP_SETUP_0A1E_MAYAHEM_TEMPLE_KICKBALL_ARENA_3 = 0xA1E
    MAP_SETUP_0A1F_GLITTER_GULCH_MINE_FUEL_DEPOT = 0xA1F
    MAP_SETUP_0A20_GLITTER_GULCH_MINE_CRUSHING_SHED = 0xA20
    MAP_SETUP_0A21_GLITTER_GULCH_MINE_FLOODED_CAVES = 0xA21
    MAP_SETUP_0A22_GLITTER_GULCH_MINE_WATER_STORAGE = 0xA22
    MAP_SETUP_0A23_GLITTER_GULCH_MINE_WATERFALL_CAVERN = 0xA23
    MAP_SETUP_0A24_GLITTER_GULCH_MINE_POWER_HUT_BASEMENT = 0xA24
    MAP_SETUP_0A25_GLITTER_GULCH_MINE_CHUFFYS_CAB = 0xA25
    MAP_SETUP_0A26_GLITTER_GULCH_MINE_INSIDE_CHUFFYS_BOILER_BOSS = 0xA26
    MAP_SETUP_0A27_GLITTER_GULCH_MINE_GLOOMY_CAVERNS = 0xA27
    MAP_SETUP_0A28_GLITTER_GULCH_MINE_GENERATOR_CAVERNS = 0xA28
    MAP_SETUP_0A29_GLITTER_GULCH_MINE_POWER_HUT = 0xA29
    MAP_SETUP_0A2A_WITCHYWORLD_WUMBAS_WIGWAM = 0xA2A
    MAP_SETUP_0A2B_WITCHYWORLD_MAIN = 0xA2B
    MAP_SETUP_0A2C_GLITTER_GULCH_MINE_TRAIN_STATION = 0xA2C
    MAP_SETUP_0A2D_GLITTER_GULCH_MINE_PROSPECTORS_HUT = 0xA2D
    MAP_SETUP_0A2E_GLITTER_GULCH_MINE_MUMBOS_SKULL = 0xA2E
    MAP_SETUP_0A2F_GLITTER_GULCH_MINE_TOXIC_GAS_CAVE = 0xA2F
    MAP_SETUP_0A30_GLITTER_GULCH_MINE_CANARY_CAVE = 0xA30
    MAP_SETUP_0A31_GLITTER_GULCH_MINE_ORDNANCE_STORAGE = 0xA31
    MAP_SETUP_0A32_WITCHYWORLD_DODGEM_DOME_LOBBY = 0xA32
    MAP_SETUP_0A33_WITCHYWORLD_DODGEM_DOME_CHALLENGE_1v1 = 0xA33
    MAP_SETUP_0A34_WITCHYWORLD_DODGEM_DOME_CHALLENGE_1v2 = 0xA34
    MAP_SETUP_0A35_WITCHYWORLD_DODGEM_DOME_CHALLENGE_1v3 = 0xA35
    MAP_SETUP_0A36_WITCHYWORLD_CRAZY_CASTLE_STOCKADE = 0xA36
    MAP_SETUP_0A37_WITCHYWORLD_CRAZY_CASTLE_LOBBY = 0xA37
    MAP_SETUP_0A38_WITCHYWORLD_CRAZY_CASTLE_PUMP_ROOM = 0xA38
    MAP_SETUP_0A39_WITCHYWORLD_BALLOON_BURST_GAME = 0xA39
    MAP_SETUP_0A3A_WITCHYWORLD_HOOP_HURRY_GAME = 0xA3A
    MAP_SETUP_0A3B_WITCHYWORLD_STAR_SPINNER = 0xA3B
    MAP_SETUP_0A3C_WITCHYWORLD_THE_INFERNO = 0xA3C
    #
    MAP_SETUP_0A3E_GLITTER_GULCH_MINE_WUMBAS_WIGWAM = 0xA3E
    MAP_SETUP_0A3F_WITCHYWORLD_CAVE_OF_HORRORS = 0xA3F
    MAP_SETUP_0A40_WITCHYWORLD_HAUNTED_CAVERNS = 0xA40
    MAP_SETUP_0A41_WITCHYWORLD_TRAIN_STATION = 0xA41
    MAP_SETUP_0A42_JOLLY_ROGERS_LAGOON_JOLLYS = 0xA42
    MAP_SETUP_0A43_JOLLY_ROGERS_LAGOON_PAWNO = 0xA43
    MAP_SETUP_0A44_JOLLY_ROGERS_LAGOON_MUMBOS_SKULL = 0xA44
    #
    MAP_SETUP_0A46_JOLLY_ROGERS_LAGOON_UFO = 0xA46
    #
    MAP_SETUP_0A49_JOLLY_ROGERS_LAGOON_ANCIENT = 0xA49
    #
    MAP_SETUP_0A4B_JOLLY_ROGERS_LAGOON_ELECTRIC_EELS_LAIR = 0xA4B
    MAP_SETUP_0A4C_JOLLY_ROGERS_LAGOON_SEAWEED_SANCTUM = 0xA4C
    MAP_SETUP_0A4D_JOLLY_ROGERS_LAGOON_INSIDE_THE_BIG_FISH = 0xA4D
    MAP_SETUP_0A4E_WITCHYWORLD_MR_PATCH = 0xA4E
    MAP_SETUP_0A4F_JOLLY_ROGERS_LAGOON_TEMPLE_OF_THE_FISHES = 0xA4F
    #
    MAP_SETUP_0A51_JOLLY_ROGERS_LAGOON_LORD_WOO_FAK_FAK = 0xA51
    #
    MAP_SETUP_0A54_JOLLY_ROGERS_LAGOON_BLUBBERS_WAVE_RACE_HIRE = 0xA54
    MAP_SETUP_0A55_GRUNTY_INDUSTRIES_OUTSIDE = 0xA55
    MAP_SETUP_0A56_GRUNTY_INDUSTRIES_FLOOR_1 = 0xA56
    MAP_SETUP_0A57_GRUNTY_INDUSTRIES_TRAIN_STATION = 0xA57
    MAP_SETUP_0A58_GRUNTY_INDUSTRIES_WORKERS_QUARTERS = 0xA58
    MAP_SETUP_0A59_GRUNTY_INDUSTRIES_TRASH_COMPACTOR = 0xA59
    MAP_SETUP_0A5A_GRUNTY_INDUSTRIES_ELEVATOR_SHAFT = 0xA5A
    MAP_SETUP_0A5B_GRUNTY_INDUSTRIES_FLOOR_2 = 0xA5B
    MAP_SETUP_0A5C_GRUNTY_INDUSTRIES_ELECTROMAGNETIC_CHAMBER = 0xA5C
    MAP_SETUP_0A5D_GRUNTY_INDUSTRIES_FLOOR_3 = 0xA5D
    MAP_SETUP_0A5E_GRUNTY_INDUSTRIES_BOILER_PLANT = 0xA5E
    MAP_SETUP_0A5F_GRUNTY_INDUSTRIES_PACKING_ROOM = 0xA5F
    MAP_SETUP_0A60_GRUNTY_INDUSTRIES_FLOOR_4 = 0xA60
    MAP_SETUP_0A61_GRUNTY_INDUSTRIES_CABLE_ROOM = 0xA61
    MAP_SETUP_0A62_GRUNTY_INDUSTRIES_QUALITY_CONTROL = 0xA62
    MAP_SETUP_0A63_GRUNTY_INDUSTRIES_FLOOR_5 = 0xA63
    MAP_SETUP_0A64_GRUNTY_INDUSTRIES_BASEMENT = 0xA64
    MAP_SETUP_0A65_GRUNTY_INDUSTRIES_REPAIR_DEPOT = 0xA65
    MAP_SETUP_0A66_GRUNTY_INDUSTRIES_WASTE_DISPOSAL = 0xA66
    MAP_SETUP_0A67_TERRYDACTYLAND_MAIN = 0xA67
    MAP_SETUP_0A68_TERRYDACTYLAND_TERRYS_NEST = 0xA68
    MAP_SETUP_0A69_TERRYDACTYLAND_TRAIN_STATION = 0xA69
    MAP_SETUP_0A6A_TERRYDACTYLAND_OOGLE_BOOGLES_CAVE = 0xA6A
    MAP_SETUP_0A6B_TERRYDACTYLAND_INSIDE_THE_MOUNTAIN = 0xA6B
    MAP_SETUP_0A6C_TERRYDACTYLAND_RIVER_PASSAGE = 0xA6C
    MAP_SETUP_0A6D_TERRYDACTYLAND_STYRACOSAURUS_FAMILY_CAVE = 0xA6D
    MAP_SETUP_0A6E_TERRYDACTYLAND_UNGA_BUNGAS_CAVE = 0xA6E
    MAP_SETUP_0A6F_TERRYDACTYLAND_STOMPING_PLAINS = 0xA6F
    MAP_SETUP_0A70_TERRYDACTYLAND_BONFIRE_CAVERN = 0xA70
    #
    MAP_SETUP_0A73_TERRYDACTYLAND_WUMBAS_WIGWAM_SMALL = 0xA73
    MAP_SETUP_0A74_GRUNTY_INDUSTRIES_WUMBAS_WIGWAM = 0xA74
    MAP_SETUP_0A75_JOLLY_ROGERS_LAGOON_WUMBAS_WIGWAM = 0xA75
    MAP_SETUP_0A76_INSIDE_CHUFFYS_WAGON = 0xA76
    MAP_SETUP_0A77_TERRYDACTYLAND_WUMBAS_WIGWAM_BIG = 0xA77
    MAP_SETUP_0A78_TERRYDACTYLAND_INSIDE_CHOMPAS_BELLY = 0xA78
    MAP_SETUP_0A79_WITCHYWORLD_SAUCER_OF_PERIL = 0xA79
    MAP_SETUP_0A7A_GRUNTY_INDUSTRIES_WATER_SUPPLY_PIPE = 0xA7A
    MAP_SETUP_0A7B_GLITTER_GULCH_MINE_WATER_SUPPLY_PIPE = 0xA7B
    MAP_SETUP_0A7C_HAILFIRE_PEAKS_LAVA_SIDE_MAIN = 0xA7C
    MAP_SETUP_0A7D_HAILFIRE_PEAKS_ICY_SIDE_MAIN = 0xA7D
    MAP_SETUP_0A7E_HAILFIRE_PEAKS_LAVA_TRAIN_STATION = 0xA7E
    MAP_SETUP_0A7F_HAILFIRE_PEAKS_ICY_TRAIN_STATION = 0xA7F
    MAP_SETUP_0A80_HAILFIRE_PEAKS_CHILLI_BILLI = 0xA80
    MAP_SETUP_0A81_HAILFIRE_PEAKS_CHILLY_WILLY = 0xA81
    MAP_SETUP_0A82_HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_LOBBY = 0xA82
    MAP_SETUP_0A83_HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_QUARTERFINAL = 0xA83
    MAP_SETUP_0A84_HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_SEMIFINAL = 0xA84
    MAP_SETUP_0A85_HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_FINAL = 0xA85
    MAP_SETUP_0A86_HAILFIRE_PEAKS_BOGGYS_IGLOO = 0xA86
    MAP_SETUP_0A87_HAILFIRE_PEAKS_ICICLE_GROTTO = 0xA87
    MAP_SETUP_0A88_HAILFIRE_PEAKS_INSIDE_THE_VOLCANO = 0xA88
    MAP_SETUP_0A89_HAILFIRE_PEAKS_MUMBOS_SKULL = 0xA89
    MAP_SETUP_0A8A_HAILFIRE_PEAKS_WUMBAS_WIGWAM = 0xA8A
    MAP_SETUP_0A8B_CLOUD_CUCKOOLAND_MAIN = 0xA8B
    MAP_SETUP_0A8C_CLOUD_CUCKOOLAND_INSIDE_TRASHCAN = 0xA8C
    MAP_SETUP_0A8D_CLOUD_CUCKOOLAND_INSIDE_CHEESEWEDGE = 0xA8D
    #
    MAP_SETUP_0A8F_CLOUD_CUCKOOLAND_CENTRAL_CAVERN = 0xA8F
    MAP_SETUP_0A90_WITCHYWORLD_CRAZY_CASTLE_STOCKADE_SOP = 0xA90
    MAP_SETUP_0A91_WITCHYWORLD_STAR_SPINNER_SOP = 0xA91
    MAP_SETUP_0A92_CLOUD_CUCKOOLAND_INSIDE_POT_O_GOLD = 0xA92
    MAP_SETUP_0A93_CLOUD_CUCKOOLAND_MUMBOS_SKULL = 0xA93
    MAP_SETUP_0A94_CLOUD_CUCKOOLAND_MINGY_JONGOS_SKULL = 0xA94
    MAP_SETUP_0A95_CLOUD_CUCKOOLAND_WUMBAS_WIGWAM = 0xA95
    MAP_SETUP_0A96_SPIRAL_MOUNTAIN_DIGGER_TUNNEL = 0xA96
    MAP_SETUP_0A97_JINJO_VILLAGE_MAIN = 0xA97
    MAP_SETUP_0A98_JINJO_VILLAGE_BOTTLES_HOUSE = 0xA98
    MAP_SETUP_0A99_JINJO_VILLAGE_KING_JINGALINGS_THRONE_ROOM = 0xA99
    MAP_SETUP_0A9A_JINJO_VILLAGE_GREEN_JINJO_FAMILY_HOUSE = 0xA9A
    MAP_SETUP_0A9B_JINJO_VILLAGE_BLACK_JINJO_FAMILY_HOUSE = 0xA9B
    MAP_SETUP_0A9C_JINJO_VILLAGE_BLUE_JINJO_FAMILY_HOUSE = 0xA9C
    MAP_SETUP_0A9D_JINJO_VILLAGE_BROWN_JINJO_FAMILY_HOUSE = 0xA9D
    #
    MAP_SETUP_0A9F_JINJO_VILLAGE_ORANGE_JINJO_FAMILY_HOUSE = 0xA9F
    MAP_SETUP_0AA0_JINJO_VILLAGE_PURPLE_JINJO_FAMILY_HOUSE = 0xAA0
    MAP_SETUP_0AA1_JINJO_VILLAGE_RED_JINJO_FAMILY_HOUSE = 0xAA1
    MAP_SETUP_0AA2_JINJO_VILLAGE_WHITE_JINJO_FAMILY_HOUSE = 0xAA2
    MAP_SETUP_0AA3_ISLE_O_HAGS_HEGGYS_EGG_SHED = 0xAA3
    MAP_SETUP_0AA4_ISLE_O_HAGS_HONEY_BS_HIVE = 0xAA4
    MAP_SETUP_0AA5_ISLE_O_HAGS_PINE_GROVE = 0xAA5
    MAP_SETUP_0AA6_ISLE_O_HAGS_CLIFF_TOP = 0xAA6
    MAP_SETUP_0AA7_ISLE_O_HAGS_MUMBOS_SKULL = 0xAA7
    MAP_SETUP_0AA8_ISLE_O_HAGS_WUMBAS_WIGWAM = 0xAA8
    MAP_SETUP_0AA9_CUTSCENE_GAME_SELECT_SCREEN = 0xAA9
    MAP_SETUP_0AAA_CUTSCENE_OPENING = 0xAAA
    MAP_SETUP_0AAB_ISLE_O_HAGS_WASTELAND = 0xAAB
    MAP_SETUP_0AAC_ISLE_O_HAGS_DIGGER_TUNNEL = 0xAAC
    MAP_SETUP_0AAD_ISLE_O_HAGS_QUAGMIRE = 0xAAD
    MAP_SETUP_0AAE_CAULDRON_KEEP_MAIN = 0xAAE
    MAP_SETUP_0AAF_CAULDRON_KEEP_GATEHOUSE = 0xAAF
    MAP_SETUP_0AB0_CAULDRON_KEEP_QUIZ = 0xAB0
    MAP_SETUP_0AB1_CAULDRON_KEEP_GUN_CHAMBER = 0xAB1
    MAP_SETUP_0AB2_CLOUD_CUCKOOLAND_CANARY_MARY_RACE = 0xAB2
    MAP_SETUP_0AB3_GRUNTY_INDUSTRIES_CLINKERS_CAVERN = 0xAB3
    MAP_SETUP_0AB4_GLITTER_GULCH_MINE_ORDNANCE_STORAGE_ENTRANCE = 0xAB4
    MAP_SETUP_0AB5_GRUNTY_INDUSTRIES_CLINKERS_CAVERN_MULTIPLAYER = 0xAB5
    MAP_SETUP_0AB6_GLITTER_GULCH_MINE_ORDNANCE_STORAGE_MULTIPLAYER = 0xAB6
    MAP_SETUP_0AB7_MAYAHEM_TEMPLE_TARGITZANS_TEMPLE_MULTIPLAYER = 0xAB7
    MAP_SETUP_0AB8_MAYAHEM_TEMPLE_CHARACTER_PARADE = 0xAB8
    MAP_SETUP_0AB9_HAILFIRE_PEAKS_ICY_SIDE_CHARACTER_PARADE = 0xAB9
    MAP_SETUP_0ABA_JINJO_VILLAGE_BOTTLES_HOUSE_CHARACTER_PARADE = 0xABA
    MAP_SETUP_0ABB_CAULDRON_KEEP_GUN_CHAMBER_CHARACTER_PARADE = 0xABB
    #
    MAP_SETUP_0AC4_GLITTER_GULCH_MINE_CANARY_MARY_RACE_1 = 0xAC4
    MAP_SETUP_0AC5_GLITTER_GULCH_MINE_CANARY_MARY_RACE_2 = 0xAC5
    MAP_SETUP_0AC6_TERRYDACTYLAND_MUMBOS_SKULL = 0xAC6
    MAP_SETUP_0AC7_GRUNTY_INDUSTRIES_MUMBOS_SKULL = 0xAC7
    MAP_SETUP_0AC8_SPIRAL_MOUNTAIN_BANJOS_HOUSE = 0xAC8
    #
    MAP_SETUP_0ACB_WITCHYWORLD_MUMBOS_SKULL = 0xACB
    MAP_SETUP_0ACC_MAYAHEM_TEMPLE_TARGITZANS_SLIGHTLY_SACRED_CHAMBER = 0xACC
    MAP_SETUP_0ACD_MAYAHEM_TEMPLE_INSIDE_TARGITZANS_TEMPLE = 0xACD
    MAP_SETUP_0ACE_MAYAHEM_TEMPLE_TARGITZANS_TEMPLE_LOBBY = 0xACE
    MAP_SETUP_0ACF_MAYAHEM_TEMPLE_TARGITZANS_TEMPLE_BOSS = 0xACF
    MAP_SETUP_0AD0_WITCHYWORLD_BALLOON_BURST_GAME_MULTIPLAYER = 0xAD0
    MAP_SETUP_0AD1_WITCHYWORLD_HOOP_HURRY_GAME_MULTIPLAYER = 0xAD1
    MAP_SETUP_0AD2_GRUNTY_INDUSTRIES_TWINKLIE_PACKING_GAME_MULTIPLAYER = 0xAD2
    MAP_SETUP_0AD3_CUTSCENE_ZOMBIFIED_THRONE_ROOM = 0xAD3
    MAP_SETUP_0AD4_MAYAHEM_TEMPLE_KICKBALL_ARENA_MULTIPLAYER = 0xAD4
    MAP_SETUP_0AD5_HAILFIRE_PEAKS_KICKBALL_STADIUM_MULTIPLAYER = 0xAD5
    MAP_SETUP_0AD6_JOLLY_ROGERS_LAGOON_SEA_BOTTOM_CAVERN = 0xAD6
    MAP_SETUP_0AD7_JOLLY_ROGERS_LAGOON_SUB_GAME_MULTIPLAYER = 0xAD7
    MAP_SETUP_0AD8_TERRYDACTYLAND_INSIDE_CHOMPAS_BELLY_MULTIPLAYER = 0xAD8
    #
    MAP_SETUP_0ADA_CLOUD_CUCKOOLAND_INSIDE_TRASHCAN_MULTIPLAYER = 0xADA
    MAP_SETUP_0ADB_WITCHYWORLD_DODGEM_DOME_CHALLENGE_MULTIPLAYER = 0xADB
    MAP_SETUP_0ADC_GRUNTY_INDUSTRIES_CLINKERS_CAVERN_ENTRANCE = 0xADC
    MAP_SETUP_0ADD_CLOUD_CUCKOOLAND_ZUBBAS_NEST_MULTIPLAYER = 0xADD
    MAP_SETUP_0ADE_CAULDRON_KEEP_QUIZ_MULTIPLAYER = 0xADE
    MAP_SETUP_0ADF_CAULDRON_KEEP_INSIDE_HAG_1 = 0xADF
    MAP_SETUP_0AE0_CUTSCENE_TITLE_SCREEN = 0xAE0
    MAP_SETUP_0AE1_CUTSCENE_SISTERS_EXPLAIN_BOB = 0xAE1
    MAP_SETUP_0AE2_CUTSCENE_GAINED_ENERGY_FROM_JINGALING = 0xAE2
    MAP_SETUP_0AE3_CUTSCENE_MEANWHILE = 0xAE3
    MAP_SETUP_0AE4_CUTSCENE_ABOUT_TO_BLAST_JINGALING = 0xAE4
    MAP_SETUP_0AE5_CUTSCENE_GETTING_ZAPPED = 0xAE5
    MAP_SETUP_0AE6_CUTSCENE_PARTY_ENDED = 0xAE6
    MAP_SETUP_0AE7_CUTSCENE_BOTTLES_GETS_HOME = 0xAE7
    MAP_SETUP_0AE8_CUTSCENE_BOTTLES_IS_BROUGHT_BACK_TO_LIFE = 0xAE8
    MAP_SETUP_0AE9_CUTSCENE_B_AND_K_ABOUT_TO_USE_BOB = 0xAE9
    MAP_SETUP_0AEA_CUTSCENE_LETS_FIX_BOTTLES_NEXT = 0xAEA
    MAP_SETUP_0AEB_CUTSCENE_PLAYING_WITH_GRUNTYS_HEAD = 0xAEB
    MAP_SETUP_0AEC_CUTSCENE_GIVING_JINGALING_BACK_LIFE = 0xAEC
    MAP_SETUP_0AED_CUTSCENE_JINGALINGS_TEMPLE_GETS_BACK_LIFE = 0xAED
    MAP_SETUP_0AEE_CUTSCENE_JINGALING_CELEBRATES_THAT_HES_BACK = 0xAEE
    MAP_SETUP_0AEF_CAULDRON_KEEP_BOSS = 0xAEF
    MAP_SETUP_0AF0_JINJO_VILLAGE_ZOMBIFIED_THRONE_ROOM = 0xAF0
    MAP_SETUP_0AF1_CUTSCENE_CREDITS = 0xAF1
    MAP_SETUP_0AF2_CUTSCENE_CHARACTER_PARADE = 0xAF2
    #
    MAP_SETUP_0AFB_JOLLY_ROGERS_LAGOON_SMUGGLERS_CAVERN = 0xAFB
    MAP_SETUP_0AFC_JOLLY_ROGERS_LAGOON_MAIN = 0xAFC
    MAP_SETUP_0AFD_JOLLY_ROGERS_LAGOON_ATLANTIS = 0xAFD
    MAP_SETUP_0AFE_JOLLY_ROGERS_LAGOON_SEA_BOTTOM = 0xAFE