###################
##### IMPORTS #####
###################

from enum import IntEnum, StrEnum, auto, unique

#####################
##### CONSTANTS #####
#####################

@unique
class CategoryEnum(IntEnum):

    @classmethod
    def name_for_value(cls, value):
        if value in cls._value2member_map_:
            return cls(value).name
        return None

    CATEGORY_4 = 0x04 # Claw Clamber End?
    LOADING_ZONE = auto()
    CATEGORY_6 = auto() # Collision Models - Collectables, Baddies?
    CATEGORY_7 = auto()
    CATEGORY_8 = auto() # Paths - Claw Clamber Boot Prints, Inserting Ice Key?
    CATEGORY_9 = auto() # Spheres - Enemy Boundary?

########################
##### OBJECT NAMES #####
########################

OBJECT_NAMES:dict = {
    CategoryEnum.LOADING_ZONE: {
        1: 'CUTSCENE_TWO_YEARS_HAVE_PASSED',
        2: 'CUTSCENE_DRILL_STARTS',
        3: 'CUTSCENE_DRILL_GOES_THROUGH_BOULDERS',
        4: 'CUTSCENE_MAGIC_TO_LIFT_BOULDER',
        5: 'CUTSCENE_REVENGE_IS_MINE',
        6: 'CUTSCENE_WITCHES_LEAVE_SPIRAL_MOUNTAIN',
        7: 'CUTSCENE_HOUSE_DESTROYED',
        8: 'CUTSCENE_PLAYING_POKER',
        9: 'CUTSCENE_EARTHQUAKE',
        10: 'CUTSCENE_IT_STOPPED',
        11: 'CUTSCENE_GET_OUT_OF_THE_HOUSE',
        12: 'CUTSCENE_COME_ON',
        13: 'GRUNTILDAS_LAIR_ENTRANCE',
        14: 'SPIRAL_MOUNTAIN_BEHIND_WATERFALL',
        15: 'SPIRAL_MOUNTAIN_MAIN',
        22: 'MAYAHEM_TEMPLE_WUMBAS_WIGWAM',
        23: 'MAYAHEM_TEMPLE_MUMBOS_SKULL',
        24: 'MAYAHEM_TEMPLE_MAIN',
        25: 'MAYAHEM_TEMPLE_PRISON_COMPOUND',
        26: 'MAYAHEM_TEMPLE_COLUMNS_VAULT',
        27: 'MAYAHEM_TEMPLE_MAYAN_KICKBALL_STADIUM',
        28: 'MAYAHEM_TEMPLE_CODE_CHAMBER',
        36: 'MAYAHEM_TEMPLE_JADE_SNAKE_GROVE',
        37: 'MAYAHEM_TEMPLE_TREASURE_CHAMBER',
        38: 'MAYAHEM_TEMPLE_KICKBALL_ARENA_1',
        39: 'GLITTER_GULCH_MINE_MAIN',
        40: 'MAYAHEM_TEMPLE_KICKBALL_ARENA_2',
        41: 'MAYAHEM_TEMPLE_KICKBALL_ARENA_3',
        42: 'GLITTER_GULCH_MINE_FUEL_DEPOT',
        43: 'GLITTER_GULCH_MINE_CRUSHING_SHED',
        44: 'GLITTER_GULCH_MINE_FLOODED_CAVES',
        45: 'GLITTER_GULCH_MINE_WATER_STORAGE',
        46: 'GLITTER_GULCH_MINE_WATERFALL_CAVERN',
        47: 'GLITTER_GULCH_MINE_POWER_HUT_BASEMENT',
        48: 'GLITTER_GULCH_MINE_CHUFFYS_CAB',
        49: 'GLITTER_GULCH_MINE_INSIDE_CHUFFYS_BOILER_BOSS',
        50: 'GLITTER_GULCH_MINE_GLOOMY_CAVERNS',
        51: 'GLITTER_GULCH_MINE_GENERATOR_CAVERNS',
        52: 'GLITTER_GULCH_MINE_POWER_HUT',
        53: 'WITCHYWORLD_WUMBAS_WIGWAM',
        54: 'WITCHYWORLD_MAIN',
        55: 'GLITTER_GULCH_MINE_TRAIN_STATION',
        56: 'GLITTER_GULCH_MINE_PROSPECTORS_HUT',
        57: 'GLITTER_GULCH_MINE_MUMBOS_SKULL',
        58: 'GLITTER_GULCH_MINE_TOXIC_GAS_CAVE',
        59: 'GLITTER_GULCH_MINE_CANARY_CAVE',
        60: 'GLITTER_GULCH_MINE_ORDNANCE_STORAGE',
        61: 'WITCHYWORLD_DODGEM_DOME_LOBBY',
        62: 'WITCHYWORLD_DODGEM_DOME_CHALLENGE_1v1',
        63: 'WITCHYWORLD_DODGEM_DOME_CHALLENGE_1v2',
        64: 'WITCHYWORLD_DODGEM_DOME_CHALLENGE_1v3',
        65: 'WITCHYWORLD_CRAZY_CASTLE_STOCKADE',
        66: 'WITCHYWORLD_CRAZY_CASTLE_LOBBY',
        67: 'WITCHYWORLD_CRAZY_CASTLE_PUMP_ROOM',
        68: 'WITCHYWORLD_BALLOON_BURST_GAME',
        69: 'WITCHYWORLD_HOOP_HURRY_GAME',
        70: 'WITCHYWORLD_STAR_SPINNER',
        71: 'WITCHYWORLD_THE_INFERNO',
        73: 'GLITTER_GULCH_MINE_WUMBAS_WIGWAM',
        74: 'WITCHYWORLD_CAVE_OF_HORRORS',
        75: 'WITCHYWORLD_HAUNTED_CAVERNS',
        76: 'WITCHYWORLD_TRAIN_STATION',
        77: 'JOLLY_ROGERS_LAGOON_JOLLYS',
        78: 'JOLLY_ROGERS_LAGOON_PAWNO',
        79: 'JOLLY_ROGERS_LAGOON_MUMBOS_SKULL',
        81: 'JOLLY_ROGERS_LAGOON_UFO',
        84: 'JOLLY_ROGERS_LAGOON_ANCIENT',
        86: 'JOLLY_ROGERS_LAGOON_ELECTRIC_EELS_LAIR',
        87: 'JOLLY_ROGERS_LAGOON_SEAWEED_SANCTUM',
        88: 'JOLLY_ROGERS_LAGOON_INSIDE_THE_BIG_FISH',
        89: 'WITCHYWORLD_MR_PATCH',
        90: 'JOLLY_ROGERS_LAGOON_TEMPLE_OF_THE_FISHES',
        92: 'JOLLY_ROGERS_LAGOON_LORD_WOO_FAK_FAK',
        95: 'JOLLY_ROGERS_LAGOON_BLUBBERS_WAVE_RACE_HIRE',
        96: 'GRUNTY_INDUSTRIES_OUTSIDE',
        97: 'GRUNTY_INDUSTRIES_FLOOR_1',
        98: 'GRUNTY_INDUSTRIES_TRAIN_STATION',
        99: 'GRUNTY_INDUSTRIES_WORKERS_QUARTERS',
        100: 'GRUNTY_INDUSTRIES_TRASH_COMPACTOR',
        101: 'GRUNTY_INDUSTRIES_ELEVATOR_SHAFT',
        102: 'GRUNTY_INDUSTRIES_FLOOR_2',
        103: 'GRUNTY_INDUSTRIES_ELECTROMAGNETIC_CHAMBER',
        104: 'GRUNTY_INDUSTRIES_FLOOR_3',
        105: 'GRUNTY_INDUSTRIES_BOILER_PLANT',
        106: 'GRUNTY_INDUSTRIES_PACKING_ROOM',
        107: 'GRUNTY_INDUSTRIES_FLOOR_4',
        108: 'GRUNTY_INDUSTRIES_CABLE_ROOM',
        109: 'GRUNTY_INDUSTRIES_QUALITY_CONTROL',
        110: 'GRUNTY_INDUSTRIES_FLOOR_5',
        111: 'GRUNTY_INDUSTRIES_BASEMENT',
        112: 'GRUNTY_INDUSTRIES_REPAIR_DEPOT',
        113: 'GRUNTY_INDUSTRIES_WASTE_DISPOSAL',
        114: 'TERRYDACTYLAND_MAIN',
        115: 'TERRYDACTYLAND_TERRYS_NEST',
        116: 'TERRYDACTYLAND_TRAIN_STATION',
        117: 'TERRYDACTYLAND_OOGLE_BOOGLES_CAVE',
        118: 'TERRYDACTYLAND_INSIDE_THE_MOUNTAIN',
        119: 'TERRYDACTYLAND_RIVER_PASSAGE',
        120: 'TERRYDACTYLAND_STYRACOSAURUS_FAMILY_CAVE',
        121: 'TERRYDACTYLAND_UNGA_BUNGAS_CAVE',
        122: 'TERRYDACTYLAND_STOMPING_PLAINS',
        123: 'TERRYDACTYLAND_BONFIRE_CAVERN',
        126: 'TERRYDACTYLAND_WUMBAS_WIGWAM_SMALL',
        127: 'GRUNTY_INDUSTRIES_WUMBAS_WIGWAM',
        128: 'JOLLY_ROGERS_LAGOON_WUMBAS_WIGWAM',
        129: 'INSIDE_CHUFFYS_WAGON',
        130: 'TERRYDACTYLAND_WUMBAS_WIGWAM_BIG',
        131: 'TERRYDACTYLAND_INSIDE_CHOMPAS_BELLY',
        132: 'WITCHYWORLD_SAUCER_OF_PERIL',
        133: 'GRUNTY_INDUSTRIES_WATER_SUPPLY_PIPE',
        134: 'GLITTER_GULCH_MINE_WATER_SUPPLY_PIPE',
        135: 'HAILFIRE_PEAKS_LAVA_SIDE_MAIN',
        136: 'HAILFIRE_PEAKS_ICY_SIDE_MAIN',
        137: 'HAILFIRE_PEAKS_LAVA_TRAIN_STATION',
        138: 'HAILFIRE_PEAKS_ICY_TRAIN_STATION',
        139: 'HAILFIRE_PEAKS_CHILLI_BILLI',
        140: 'HAILFIRE_PEAKS_CHILLY_WILLY',
        141: 'HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_LOBBY',
        142: 'HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_QUARTERFINAL',
        143: 'HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_SEMIFINAL',
        144: 'HAILFIRE_PEAKS_COLOSSEUM_KICKBALL_STADIUM_FINAL',
        145: 'HAILFIRE_PEAKS_BOGGYS_IGLOO',
        146: 'HAILFIRE_PEAKS_ICICLE_GROTTO',
        147: 'HAILFIRE_PEAKS_INSIDE_THE_VOLCANO',
        148: 'HAILFIRE_PEAKS_MUMBOS_SKULL',
        149: 'HAILFIRE_PEAKS_WUMBAS_WIGWAM',
        150: 'CLOUD_CUCKOOLAND_MAIN',
        151: 'CLOUD_CUCKOOLAND_INSIDE_TRASHCAN',
        152: 'CLOUD_CUCKOOLAND_INSIDE_CHEESEWEDGE',
        154: 'CLOUD_CUCKOOLAND_CENTRAL_CAVERN',
        155: 'WITCHYWORLD_CRAZY_CASTLE_STOCKADE_SOP',
        156: 'WITCHYWORLD_STAR_SPINNER_SOP',
        157: 'CLOUD_CUCKOOLAND_INSIDE_POT_O_GOLD',
        158: 'CLOUD_CUCKOOLAND_MUMBOS_SKULL',
        159: 'CLOUD_CUCKOOLAND_MINGY_JONGOS_SKULL',
        160: 'CLOUD_CUCKOOLAND_WUMBAS_WIGWAM',
        161: 'SPIRAL_MOUNTAIN_DIGGER_TUNNEL',
        162: 'JINJO_VILLAGE_MAIN',
        163: 'JINJO_VILLAGE_BOTTLES_HOUSE',
        164: 'JINJO_VILLAGE_KING_JINGALINGS_THRONE_ROOM',
        165: 'JINJO_VILLAGE_GREEN_JINJO_FAMILY_HOUSE',
        166: 'JINJO_VILLAGE_BLACK_JINJO_FAMILY_HOUSE',
        167: 'JINJO_VILLAGE_BLUE_JINJO_FAMILY_HOUSE',
        168: 'JINJO_VILLAGE_BROWN_JINJO_FAMILY_HOUSE',
        170: 'JINJO_VILLAGE_ORANGE_JINJO_FAMILY_HOUSE',
        171: 'JINJO_VILLAGE_PURPLE_JINJO_FAMILY_HOUSE',
        172: 'JINJO_VILLAGE_RED_JINJO_FAMILY_HOUSE',
        173: 'JINJO_VILLAGE_WHITE_JINJO_FAMILY_HOUSE',
        174: 'ISLE_O_HAGS_HEGGYS_EGG_SHED',
        175: 'ISLE_O_HAGS_HONEY_BS_HIVE',
        176: 'ISLE_O_HAGS_PINE_GROVE',
        177: 'ISLE_O_HAGS_CLIFF_TOP',
        178: 'ISLE_O_HAGS_MUMBOS_SKULL',
        179: 'ISLE_O_HAGS_WUMBAS_WIGWAM',
        180: 'CUTSCENE_GAME_SELECT_SCREEN',
        181: 'CUTSCENE_OPENING',
        182: 'ISLE_O_HAGS_WASTELAND',
        183: 'ISLE_O_HAGS_DIGGER_TUNNEL',
        184: 'ISLE_O_HAGS_QUAGMIRE',
        185: 'CAULDRON_KEEP_MAIN',
        186: 'CAULDRON_KEEP_GATEHOUSE',
        187: 'CAULDRON_KEEP_QUIZ',
        188: 'CAULDRON_KEEP_GUN_CHAMBER',
        189: 'CLOUD_CUCKOOLAND_CANARY_MARY_RACE',
        190: 'GRUNTY_INDUSTRIES_CLINKERS_CAVERN',
        191: 'GLITTER_GULCH_MINE_ORDNANCE_STORAGE_ENTRANCE',
        192: 'GRUNTY_INDUSTRIES_CLINKERS_CAVERN_MULTIPLAYER',
        193: 'GLITTER_GULCH_MINE_ORDNANCE_STORAGE_MULTIPLAYER',
        194: 'MAYAHEM_TEMPLE_TARGITZANS_TEMPLE_MULTIPLAYER',
        195: 'MAYAHEM_TEMPLE_CHARACTER_PARADE',
        196: 'HAILFIRE_PEAKS_ICY_SIDE_CHARACTER_PARADE',
        197: 'JINJO_VILLAGE_BOTTLES_HOUSE_CHARACTER_PARADE',
        198: 'CAULDRON_KEEP_GUN_CHAMBER_CHARACTER_PARADE',
        207: 'GLITTER_GULCH_MINE_CANARY_MARY_RACE_1',
        208: 'GLITTER_GULCH_MINE_CANARY_MARY_RACE_2',
        209: 'TERRYDACTYLAND_MUMBOS_SKULL',
        210: 'GRUNTY_INDUSTRIES_MUMBOS_SKULL',
        211: 'SPIRAL_MOUNTAIN_BANJOS_HOUSE',
        214: 'WITCHYWORLD_MUMBOS_SKULL',
        215: 'MAYAHEM_TEMPLE_TARGITZANS_SLIGHTLY_SACRED_CHAMBER',
        216: 'MAYAHEM_TEMPLE_INSIDE_TARGITZANS_TEMPLE',
        217: 'MAYAHEM_TEMPLE_TARGITZANS_TEMPLE_LOBBY',
        218: 'MAYAHEM_TEMPLE_TARGITZANS_TEMPLE_BOSS',
        219: 'WITCHYWORLD_BALLOON_BURST_GAME_MULTIPLAYER',
        220: 'WITCHYWORLD_HOOP_HURRY_GAME_MULTIPLAYER',
        221: 'GRUNTY_INDUSTRIES_TWINKLIE_PACKING_GAME_MULTIPLAYER',
        222: 'CUTSCENE_ZOMBIFIED_THRONE_ROOM',
        223: 'MAYAHEM_TEMPLE_KICKBALL_ARENA_MULTIPLAYER',
        224: 'HAILFIRE_PEAKS_KICKBALL_STADIUM_MULTIPLAYER',
        225: 'JOLLY_ROGERS_LAGOON_SEA_BOTTOM_CAVERN',
        226: 'JOLLY_ROGERS_LAGOON_SUB_GAME_MULTIPLAYER',
        227: 'TERRYDACTYLAND_INSIDE_CHOMPAS_BELLY_MULTIPLAYER',
        229: 'CLOUD_CUCKOOLAND_INSIDE_TRASHCAN_MULTIPLAYER',
        230: 'WITCHYWORLD_DODGEM_DOME_CHALLENGE_MULTIPLAYER',
        231: 'GRUNTY_INDUSTRIES_CLINKERS_CAVERN_ENTRANCE',
        232: 'CLOUD_CUCKOOLAND_ZUBBAS_NEST_MULTIPLAYER',
        233: 'CAULDRON_KEEP_QUIZ_MULTIPLAYER',
        234: 'CAULDRON_KEEP_INSIDE_HAG_1',
        235: 'CUTSCENE_TITLE_SCREEN',
        236: 'CUTSCENE_SISTERS_EXPLAIN_BOB',
        237: 'CUTSCENE_GAINED_ENERGY_FROM_JINGALING',
        238: 'CUTSCENE_MEANWHILE',
        239: 'CUTSCENE_ABOUT_TO_BLAST_JINGALING',
        240: 'CUTSCENE_GETTING_ZAPPED',
        241: 'CUTSCENE_PARTY_ENDED',
        242: 'CUTSCENE_BOTTLES_GETS_HOME',
        243: 'CUTSCENE_BOTTLES_IS_BROUGHT_BACK_TO_LIFE',
        244: 'CUTSCENE_B_AND_K_ABOUT_TO_USE_BOB',
        245: 'CUTSCENE_LETS_FIX_BOTTLES_NEXT',
        246: 'CUTSCENE_PLAYING_WITH_GRUNTYS_HEAD',
        247: 'CUTSCENE_GIVING_JINGALING_BACK_LIFE',
        248: 'CUTSCENE_JINGALINGS_TEMPLE_GETS_BACK_LIFE',
        249: 'CUTSCENE_JINGALING_CELEBRATES_THAT_HES_BACK',
        250: 'CAULDRON_KEEP_BOSS',
        251: 'JINJO_VILLAGE_ZOMBIFIED_THRONE_ROOM',
        252: 'CUTSCENE_CREDITS',
        253: 'CUTSCENE_CHARACTER_PARADE',
        262: 'JOLLY_ROGERS_LAGOON_SMUGGLERS_CAVERN',
        263: 'JOLLY_ROGERS_LAGOON_MAIN',
        264: 'JOLLY_ROGERS_LAGOON_ATLANTIS',
        265: 'JOLLY_ROGERS_LAGOON_SEA_BOTTOM',
    },
    CategoryEnum.CATEGORY_6: {
        0: "Move BK Here", # For Talking To Mumbo?
        3: "Bone Door", # Treasure Chamber
        30: "Warp Pad Entry 1?",
        31: "Warp Pad Entry 2?",
        32: "Warp Pad Entry 3?",
        33: "Warp Pad Entry 4?",
        268: "Sslumber (Sleeping Snake)",
        269: "Snake Statue Head (Outside Treasure Chamber)",
        271: "Brown Boulder (Breakable)",
        272: "Code Chamber Door (Breakable)",
        273: "Snapdragon (Wall Enemy)",
        274: "Moggy (Cat Enemy)",
        275: "Sput Sput (Rotating Stone Enemy)",
        276: "Stony (Hint Stone NPCs)",
        277: "Chief Bloatazin (Treasure Chamber)",
        278: "Officer Unogopaz (Kickball Cat Guard)",
        281: "Bang Box (TNT Crate Baddie)",
        282: "Diggit (Shovel Baddie)",
        304: "Button", # Mayahem Temple Treasure Chamber
        305: "Ugger (Green Baddie)",
        308: "Gruntdactyl (Flying Dinosaur Baddie)",
        309: "Cheato",
        313: "Cactus Of Strength Button",
        319: "Mrs Boggy", # Witchyworld
        320: "Soggy (Boggys Kid)",
        324: "Fruity (Slot Machine Baddie)",
        336: "Billy Bob (Underground Cowboy Baddie)",
        342: "Split Up Pad - Kazooie",
        343: "Split Up Pad - Banjo",
        355: "Golden Goliath",
        357: "Coin Box",
        362: "Claw Clamber Boots",
        # 363: "Claw Clamber Boots Start?",
        366: "Climb Base (Ladder)",
        329: "TNT Barrel (Transformation Interactable)",
        400: "Mumbo Jumbo (In Skull)",
        408: "Sign Post",
        411: "Boniva (Cow)",
        423: "Jamjars Hatch",
        425: "Bottles Molehill",
        443: "Mist (Waterfall/River)",
        462: "Red Feather",
        463: "Gold Feather",
        471: "Note Nest",
        472: "Treble Clef",
        485: "Warp Pad",
        489: "Egg Nest",
        496: "Rareware Box",
        501: "Jinjo",
        502: "Jiggy",
        503: "Empty Honeycomb",
        504: "Glowbo",
        505: "Climb Base (Vine)",
        506: "Climb Peak (Vine)",
        507: "Climb Peak (Ladder)",
        513: "Cheato Page",
        528: "Shock Jump Pad",
        529: "Beehive",
        538: "Turbo Trainers",
        539: "Mega Glowbo",
        553: "Honeycomb",
        558: "Wading Boots",
        564: "Flight Pad",
        645: "Train Station Button - Hailfire Peaks Lava Side",
        648: "Portcullis (Hailfire Peaks)",
        673: "Humba Wumba",
        675: "Saucer Of Peril In Box",
        688: "Mumbo Pad",
        802: "Green Boulder (Breakable)",
        807: "Jippo Jim (Rat With Hammer Baddie)",
        815: "Burger Stand",
        816: "Burger Stand Button",
        817: "French Fry Stand",
        818: "French Fry Stand Button",
        834: "Electric Gate (Breakable)",
        838: "Sabreman",
        898: "Chuffy Train Sign",
        940: "Torch Fire",
        972: "Van Door",
        979: "Electric Fence",
        993: "Mildred (Ice Cube Baddie)",
        994: "Ice Cube (Breakable)",
        997: "Biggyfoot (Abominable Snowman Baddie)",
        998: "Biggafoot (Abominable Snowman Guard Baddie)",
        1001: "Hot Hand (Lava Hand Baddie)",
        1007: "Roysten",
        1025: "Gobgoyle (Gargoyle Baddie)",
        1050: "Train Station Button - Hailfire Peaks Icy Side",
        1064: "Hot Water Pool Door To JRL",
        1112: "Alien Baby",
        1122: "Hothead (Flying Fire Baddie)",
        1138: "Talon Torpedo Boulder",
        1157: "Oil Mining Button",
        1170: "Banjo Switch",
        1177: "Talon Torpedo Wall",
        1190: "Feather Nest",
        1210: "Boggys Fish",
        1212: "Dead Bottles",
        1225: "Treasure Chamber Top Outside Door",
        1260: "Spiral Mountain Klungo",
        1274: "Grenade Breakable Wall",
        1298: "Ice Key Safe Door",
        1306: "BK Cartridge",
    },
    CategoryEnum.CATEGORY_7: {},
    CategoryEnum.CATEGORY_8: {},
    CategoryEnum.CATEGORY_9: {},
}